# Generated by Django 4.2.7 on 2024-05-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_alter_academico_prestamos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='codigo',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
    ]
