# Generated by Django 4.2.7 on 2024-05-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_libro_codigo_alter_libro_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='codigo',
            new_name='codigolibro',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='codigolibro',
            field=models.CharField(default=1, max_length=25),
        ),
    ]
