# Generated by Django 4.2.7 on 2024-05-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_rename_codigo_libro_codigolibro_prestamo_codigolibro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='codigolibro',
            field=models.CharField(default=1, max_length=25, primary_key=True, serialize=False),
        ),
    ]
