# Generated by Django 4.2.7 on 2024-06-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_alter_libro_codigolibro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=35),
        ),
    ]
